export { PaymentsCategoryPageContainer } from './payments/payments-category-page/payments-category-page.container'
export { ServicePage } from './payments'
export { PaymentsCategoryPage } from './payments'
export { PaymentCategoryListPage } from './payments'
export { MainPage } from './main'
export { AtmsPage } from './atms'
export { ProfilePage } from './profile'
